# SPDX-FileCopyrightText: 2022 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: GPL-2.0-or-later
name: Windows Build
on:
  push:
    paths:
      - '.github/workflows/windows-build.yml'
  workflow_dispatch:
  workflow_call:
    secrets:
      NEXTCLOUD_BRANCH_ACCESS_TOKEN:
        required: true

jobs:
  build:
    name: Windows Build
    runs-on: windows-2022
    permissions: 
      contents: read
    env:
      BASE_WORKSPACE: ${{ github.workspace }}/nextcloud-desktop
      CRAFT_TARGET: windows-msvc2022_64-cl
      CHOCO_LOCATION: ${{ github.workspace }}/nextcloud-desktop/choco
      COBERTURA_COVERAGE_FILE:  ${{ github.workspace }}/nextcloud-desktop/cobertura_coverage/coverage.xml
      CRAFT_MASTER_LOCATION:  ${{ github.workspace }}/nextcloud-desktop/CraftMaster
      CRAFT_MASTER_CONFIG:  ${{ github.workspace }}/nextcloud-desktop/craftmaster.ini
      ARCHIVE_VERABLE: -zcvf
      ARCHIVE_PERFIX: .zip
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Checkout  repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          repository: zonghewang/nextcloud-desktop
          token: ${{ secrets.NEXTCLOUD_BRANCH_ACCESS_TOKEN }}
          path: nextcloud-desktop

      - name: Cleanup
        run: |
          function clearn_caches() {
            echo "init"
            $cacheKeysForPR=$(gh cache list --key ${{ env.CACHE_KEY }} --json key --jq '.[].key')
            echo $cacheKeysForPR
            foreach ($cacheKey in $cacheKeysForPR) {
                if ($cacheKey -ceq "${{ env.CACHE_KEY }}")  {
                  echo "hint cache $cacheKey"
                  gh cache delete $cacheKey
                  echo "delete cache $cacheKey done"
                }
             }
            echo "Done"
          }
          clearn_caches
        env:
          GH_TOKEN: ${{ secrets.NEXTCLOUD_BRANCH_ACCESS_TOKEN }}
          CACHE_KEY: ${{ runner.os }}-build-${{ hashFiles(env.CRAFT_MASTER_CONFIG) }}

      - name: Discover cached Craft directories
        id: windows-cache-craft-restore
        uses: actions/cache/restore@v4.3.0 # v4.3.0
        with:
          path: |
            ${{ env.CHOCO_LOCATION }}
            ${{ env.CRAFT_MASTER_LOCATION }}
            ${{ env.BASE_WORKSPACE }}/${{ env.CRAFT_TARGET }}
          key: ${{ runner.os }}-cache-${{ hashFiles(env.CRAFT_MASTER_CONFIG) }}

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.12'

      - name: Install Craft Master with Nextcloud Client Deps
        if: steps.windows-cache-craft-restore.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          & cmd /C "git clone -q --depth=1 https://github.com/KDE/craftmaster.git ${{ env.CRAFT_MASTER_LOCATION }} 2>&1"
          
          function craft() {
              python "${{ env.CRAFT_MASTER_LOCATION }}/CraftMaster.py" --config "${{ env.CRAFT_MASTER_CONFIG }}" --target ${{ env.CRAFT_TARGET }} -c $args
              if($LASTEXITCODE -ne 0) {exit $LASTEXITCODE}
          }
          
          craft --add-blueprint-repository "https://github.com/nextcloud/craft-blueprints-kde.git|next|"
          craft --add-blueprint-repository "https://oauth2:${{ secrets.NEXTCLOUD_BRANCH_ACCESS_TOKEN }}@github.com/zonghewang/nextcloud-desktop-client-blueprints.git|master|"
          craft craft
          craft --install-deps nextcloud-client


      - name: Install choco
        # if: steps.build-windows-cache-craft-restore.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          choco source add -n=chocoOfflineControl -s="file:///${{ env.CHOCO_LOCATION }}/" --priority=5
          choco install -f inkscape png2imagemagickico --cache-location="${{ env.CHOCO_LOCATION }}/" 

      - name: Compile
        shell: pwsh
        run: |
          function craft() {
              python "${{ env.CRAFT_MASTER_LOCATION }}/CraftMaster.py" --config "${{ env.CRAFT_MASTER_CONFIG }}" --target ${{ env.CRAFT_TARGET }} -c $args
              if($LASTEXITCODE -ne 0) {exit $LASTEXITCODE}
          }
          
          craft --src-dir ${{ env.BASE_WORKSPACE }} nextcloud-client

      - name: Save cached Craft directories
        id: build-windows-cache-craft-save
        uses: actions/cache/save@v4.3.0
        with:
          path: |
            ${{ env.CHOCO_LOCATION }}
            ${{ env.CRAFT_MASTER_LOCATION }}
            ${{ env.BASE_WORKSPACE }}/${{ env.CRAFT_TARGET }}
          key: ${{ runner.os }}-build-${{ hashFiles(env.CRAFT_MASTER_CONFIG) }}

  call-package-workflow:
    needs: build
    uses: ./.github/workflows/windows-package.yml
    secrets:
      NEXTCLOUD_BRANCH_ACCESS_TOKEN: ${{ secrets.NEXTCLOUD_BRANCH_ACCESS_TOKEN }}

          
